Since the system is so big, we can not call the NUPs by chain in VMD. Therefore, we use this script to call the NUPs by the starting and ending indices.

In [1]:
import numpy as np
# import matplotlib as mpl
import matplotlib.pyplot as plt
import mdtraj as md
import pandas as pd
import pickle

import sys
sys.path.append('/home/ed31/Documents/LargeSystem/npc/')
from npc_ana_tool import *

In [2]:
N_subunit_CA

np.int64(78030)

In [3]:
ring_info

{'CR_all': ['CR',
  'CR (CNC/Y)',
  'CR (FG)',
  'CR (unique)',
  'CR (cytoplasmic filament)'],
 'IR_all': ['IR', 'IR (CNT)', 'IR (FG)'],
 'NR_all': ['NR', 'NR (CNC/Y)', 'NR (FG)', 'NR (unique)'],
 'LR_all': ['LR', 'transmembrane/IR'],
 'Bridge': ['NR-IR bridge', 'CR-IR bridge']}

In [4]:
df_chain_info.head()

,new_id,model,start,end,CA_start,CA_end,Nup,Chain ID,Ring
0,00,7r5k,0,6084,0,755,Nup358 (RBP2),A,CR (unique)
1,01,7r5k,6085,12169,756,1511,Nup358 (RBP2),B,CR (unique)
2,02,7r5k,12170,18254,1512,2267,Nup358 (RBP2),C,CR (unique)
3,03,7r5k,18255,24339,2268,3023,Nup358 (RBP2),D,CR (unique)
4,04,7r5k,24340,30424,3024,3779,Nup358 (RBP2),E,CR (unique)

In [6]:
df_chain_info[df_chain_info['Ring'].isin(ring_info['IR_all'])].head()

   new_id model   start     end  CA_start  CA_end     Nup Chain ID Ring
15     A0  7r5k  148637  155204     19194   20011   Nup93        P   IR
16     A1  7r5k  155205  161772     20012   20829   Nup93        Q   IR
17     A2  7r5k  161773  168340     20830   21647   Nup93        R   IR
18     A3  7r5k  168341  174908     21648   22465   Nup93        S   IR
22     B0  7r5k  192489  206234     24644   26391  Nup188        W   IR

# Index to Nup

In [7]:
def index2nup(i):
    j = i%78030
    return df_chain_info.query(f"CA_start < @j & CA_end > @j")

In [17]:
index2nup(233)

,new_id,model,start,end,CA_start,CA_end,Nup,Chain ID,Ring
0,00,7r5k,0,6084,0,755,Nup358 (RBP2),A,CR (unique)

# Rings indices

In [8]:
CR_start = []
CR_end = []
start = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['CR_all'])]['CA_start'])
end = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['CR_all'])]['CA_end'])
CR_start.append(start[0])
for i in range(1, len(start)):
    if start[i] == 1+end[i - 1]:
        continue
    else:
        CR_start.append(start[i])
        CR_end.append(end[i-1])
CR_end.append(end[-1])

In [ ]:
# Subunit 1
k = 0
print("index " + " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(CR_start, CR_end)]))

# All subunits
CR_CA = "index "
for k in range(8):

    CR_CA += " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(CR_start, CR_end)])
    CR_CA += " "
print(CR_CA)

index 0 to 3779 22466 to 23917 32162 to 36183 51035 to 53377 55550 to 57113 58678 to 60023 61370 to 61971 62574 to 63219 63866 to 65175 66486 to 67175 67866 to 70663 73462 to 74105 76758 to 76926 77022 to 78029
index 0 to 3779 22466 to 23917 32162 to 36183 51035 to 53377 55550 to 57113 58678 to 60023 61370 to 61971 62574 to 63219 63866 to 65175 66486 to 67175 67866 to 70663 73462 to 74105 76758 to 76926 77022 to 78029 78030 to 81809 100496 to 101947 110192 to 114213 129065 to 131407 133580 to 135143 136708 to 138053 139400 to 140001 140604 to 141249 141896 to 143205 144516 to 145205 145896 to 148693 151492 to 152135 154788 to 154956 155052 to 156059 156060 to 159839 178526 to 179977 188222 to 192243 207095 to 209437 211610 to 213173 214738 to 216083 217430 to 218031 218634 to 219279 219926 to 221235 222546 to 223235 223926 to 226723 229522 to 230165 232818 to 232986 233082 to 234089 234090 to 237869 256556 to 258007 266252 to 270273 285125 to 287467 289640 to 291203 292768 to 294113 295460 to 296061 296664 to 297309 297956 to 299265 300576 to 301265 301956 to 304753 307552 to 308195 310848 to 311016 311112 to 312119 312120 to 315899 334586 to 336037 344282 to 348303 363155 to 365497 367670 to 369233 370798 to 372143 373490 to 374091 374694 to 375339 375986 to 377295 378606 to 379295 379986 to 382783 385582 to 386225 388878 to 389046 389142 to 390149 390150 to 393929 412616 to 414067 422312 to 426333 441185 to 443527 445700 to 447263 448828 to 450173 451520 to 452121 452724 to 453369 454016 to 455325 456636 to 457325 458016 to 460813 463612 to 464255 466908 to 467076 467172 to 468179 468180 to 471959 490646 to 492097 500342 to 504363 519215 to 521557 523730 to 525293 526858 to 528203 529550 to 530151 530754 to 531399 532046 to 533355 534666 to 535355 536046 to 538843 541642 to 542285 544938 to 545106 545202 to 546209 546210 to 549989 568676 to 570127 578372 to 582393 597245 to 599587 601760 to 603323 604888 to 606233 607580 to 608181 608784 to 609429 610076 to 611385 612696 to 613385 614076 to 616873 619672 to 620315 622968 to 623136 623232 to 624239

In [11]:
IR_start = []
IR_end = []
start = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['IR_all'])]['CA_start'])
end = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['IR_all'])]['CA_end'])
IR_start.append(start[0])
for i in range(1, len(start)):
    if start[i] == 1+end[i - 1]:
        continue
    else:
        IR_start.append(start[i])
        IR_end.append(end[i-1])
IR_end.append(end[-1])

In [ ]:
# Subunit 1
k = 0
print("index " + " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(IR_start, IR_end)]))

# All subunits
IR_CA = "index "
for k in range(8):

    IR_CA += " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(IR_start, IR_end)])
    IR_CA += " "
print(IR_CA)

index 19194 to 22465 24644 to 32161 38195 to 43442 47163 to 51034 76927 to 77002
index 19194 to 22465 24644 to 32161 38195 to 43442 47163 to 51034 76927 to 77002 97224 to 100495 102674 to 110191 116225 to 121472 125193 to 129064 154957 to 155032 175254 to 178525 180704 to 188221 194255 to 199502 203223 to 207094 232987 to 233062 253284 to 256555 258734 to 266251 272285 to 277532 281253 to 285124 311017 to 311092 331314 to 334585 336764 to 344281 350315 to 355562 359283 to 363154 389047 to 389122 409344 to 412615 414794 to 422311 428345 to 433592 437313 to 441184 467077 to 467152 487374 to 490645 492824 to 500341 506375 to 511622 515343 to 519214 545107 to 545182 565404 to 568675 570854 to 578371 584405 to 589652 593373 to 597244 623137 to 623212

In [14]:
NR_start = []
NR_end = []
start = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['NR_all'])]['CA_start'])
end = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['NR_all'])]['CA_end'])
NR_start.append(start[0])
for i in range(1, len(start)):
    if start[i] == 1+end[i - 1]:
        continue
    else:
        NR_start.append(start[i])
        NR_end.append(end[i-1])
NR_end.append(end[-1])

In [15]:
# Subunit 1
k = 0
print("index " + " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(NR_start, NR_end)]))

# All subunits
NR_CA = "index "
for k in range(8):

    NR_CA += " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(NR_start, NR_end)])
    NR_CA += " "
print(NR_CA)

index 23918 to 24643 36184 to 38194 53378 to 55549 57114 to 58677 60024 to 61369 61972 to 62573 63220 to 63865 65176 to 66485 67176 to 67865 70664 to 73461 74106 to 76757 77003 to 77021
index 23918 to 24643 36184 to 38194 53378 to 55549 57114 to 58677 60024 to 61369 61972 to 62573 63220 to 63865 65176 to 66485 67176 to 67865 70664 to 73461 74106 to 76757 77003 to 77021 101948 to 102673 114214 to 116224 131408 to 133579 135144 to 136707 138054 to 139399 140002 to 140603 141250 to 141895 143206 to 144515 145206 to 145895 148694 to 151491 152136 to 154787 155033 to 155051 179978 to 180703 192244 to 194254 209438 to 211609 213174 to 214737 216084 to 217429 218032 to 218633 219280 to 219925 221236 to 222545 223236 to 223925 226724 to 229521 230166 to 232817 233063 to 233081 258008 to 258733 270274 to 272284 287468 to 289639 291204 to 292767 294114 to 295459 296062 to 296663 297310 to 297955 299266 to 300575 301266 to 301955 304754 to 307551 308196 to 310847 311093 to 311111 336038 to 336763 348304 to 350314 365498 to 367669 369234 to 370797 372144 to 373489 374092 to 374693 375340 to 375985 377296 to 378605 379296 to 379985 382784 to 385581 386226 to 388877 389123 to 389141 414068 to 414793 426334 to 428344 443528 to 445699 447264 to 448827 450174 to 451519 452122 to 452723 453370 to 454015 455326 to 456635 457326 to 458015 460814 to 463611 464256 to 466907 467153 to 467171 492098 to 492823 504364 to 506374 521558 to 523729 525294 to 526857 528204 to 529549 530152 to 530753 531400 to 532045 533356 to 534665 535356 to 536045 538844 to 541641 542286 to 544937 545183 to 545201 570128 to 570853 582394 to 584404 599588 to 601759 603324 to 604887 606234 to 607579 608182 to 608783 609430 to 610075 611386 to 612695 613386 to 614075 616874 to 619671 620316 to 622967 623213 to 623231

In [16]:
# Ring info
LR_start = []
LR_end = []
start = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['LR_all'])]['CA_start'])
end = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['LR_all'])]['CA_end'])
LR_start.append(start[0])
for i in range(1, len(start)):
    if start[i] == 1+end[i - 1]:
        continue
    else:
        LR_start.append(start[i])
        LR_end.append(end[i-1])
LR_end.append(end[-1])

In [17]:

# Subunit 1
k = 0
print("index " + " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(LR_start, LR_end)]))

# All subunits
LR_CA = "index "
for k in range(8):

    LR_CA += " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(LR_start, LR_end)])
    LR_CA += " "
print(LR_CA)

index 3780 to 19193 46067 to 47162
index 3780 to 19193 46067 to 47162 81810 to 97223 124097 to 125192 159840 to 175253 202127 to 203222 237870 to 253283 280157 to 281252 315900 to 331313 358187 to 359282 393930 to 409343 436217 to 437312 471960 to 487373 514247 to 515342 549990 to 565403 592277 to 593372

In [18]:
Bridge_start = []
Bridge_end = []
start = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['Bridge'])]['CA_start'])
end = list(df_chain_info[df_chain_info['Ring'].isin(ring_info['Bridge'])]['CA_end'])
Bridge_start.append(start[0])
for i in range(1, len(start)):
    if start[i] == 1+end[i - 1]:
        continue
    else:
        Bridge_start.append(start[i])
        Bridge_end.append(end[i-1])
Bridge_end.append(end[-1])

In [19]:
# Subunit 1
k = 0
print("index " + " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(Bridge_start, Bridge_end)]))

# All subunits
Bridge_CA = "index "
for k in range(8):

    Bridge_CA += " ".join([f"{i+N_subunit_CA*k} to {j+N_subunit_CA*k}" for i, j in zip(Bridge_start, Bridge_end)])
    Bridge_CA += " "
print(Bridge_CA)

index 43443 to 46066
index 43443 to 46066 121473 to 124096 199503 to 202126 277533 to 280156 355563 to 358186 433593 to 436216 511623 to 514246 589653 to 592276

# Nup indices

In [20]:
# k is the subunit index, starting from 0 to 7
# continuous determines whether the two ends of the indices are merged or separated between NUPs
def indices_list(df_tmp, k = 0, continuous = True):
    start = []
    end = []
    start_tmp = list(df_tmp['CA_start'])
    end_tmp = list(df_tmp['CA_end'])
    if continuous:
        start.append(start_tmp[0])
        for i in range(1, len(start_tmp)):
            if start_tmp[i] == 1+end_tmp[i - 1]:
                continue
            else:
                start.append(start_tmp[i])
                end.append(end_tmp[i-1])
        end.append(end_tmp[-1])
    else:
        start = start_tmp
        end = end_tmp
    return [f"{i+k*N_subunit_CA} to {j+k*N_subunit_CA}" for i, j in zip(start, end)]

def get_indices_list_vmd(df_tmp, k = 0, continuous = True):
    idx =  indices_list(df_tmp, k, continuous)
    return "index " + " ".join(idx)

In [21]:
df_tmp = df_chain_info.loc[[31]]
print(get_indices_list_vmd(df_tmp, 7))

index 587029 to 588340

In [13]:
df_tmp = df_chain_info.query('Ring == "CR (CNC/Y)" & Nup != "Nup133"')
print(get_indices_list_vmd(df_tmp, 0))

index 55550 to 56331 56332 to 57113 58678 to 59350 59351 to 60023 61370 to 61670 61671 to 61971 62574 to 62896 62897 to 63219 63866 to 64520 64521 to 65175 66486 to 66830 66831 to 67175 67866 to 69264 69265 to 70663 73462 to 73783 73784 to 74105

In [68]:
df_tmp = df_chain_info.query('Nup == "NDC1"')
print(get_indices_list_vmd(df_tmp, 0, continuous=False))

df_tmp = df_chain_info.query('Nup == "Aladin"')
print(get_indices_list_vmd(df_tmp, 0, continuous=False))

index 46067 to 46614 46615 to 47162
index 18428 to 18810 18811 to 19193

In [27]:
for key in ring_info['CR_all']:
    df_tmp = df_chain_info.query(f'Ring == "{key}"')
    print(get_indices_list_vmd(df_tmp, 0))

print("************************")

for key in ring_info['CR_all']:
    df_tmp = df_chain_info.query(f'Ring == "{key}"')
    print(get_indices_list_vmd(df_tmp, 1))

index 22466 to 23191 23192 to 23917 32162 to 34172 34173 to 36183
index 51206 to 52291 52292 to 53377 55550 to 56331 56332 to 57113 58678 to 59350 59351 to 60023 61370 to 61670 61671 to 61971 62574 to 62896 62897 to 63219 63866 to 64520 64521 to 65175 66486 to 66830 66831 to 67175 67866 to 69264 69265 to 70663 73462 to 73783 73784 to 74105
index 76908 to 76926
index 0 to 755 756 to 1511 1512 to 2267 2268 to 3023 3024 to 3779
index 51035 to 51205 76758 to 76907 77022 to 77294 77295 to 78029
************************
index 100496 to 101221 101222 to 101947 110192 to 112202 112203 to 114213
index 129236 to 130321 130322 to 131407 133580 to 134361 134362 to 135143 136708 to 137380 137381 to 138053 139400 to 139700 139701 to 140001 140604 to 140926 140927 to 141249 141896 to 142550 142551 to 143205 144516 to 144860 144861 to 145205 145896 to 147294 147295 to 148693 151492 to 151813 151814 to 152135
index 154938 to 154956
index 78030 to 78785 78786 to 79541 79542 to 80297 80298 to 81053 81054 to 81809
index 129065 to 129235 154788 to 154937 155052 to 155324 155325 to 156059

In [38]:
df_tmp = df_chain_info.loc[[15, 24]]
print(get_indices_list_vmd(df_tmp, 1))

index 97224 to 98041 106170 to 108180

# Discrete indices

In [22]:
def get_indices_vmd(input):
    return("index " + " ".join(map(str, input)))